#!/bin/sh

wallpaper_dir=~/.config/wall.png

[ -f "$1" ] && cp "$1" $wallpaper_dir && notify-send -i $wallpaper_dir "Wallpaper Changed"

[ -d "$1" ] && cp $(find "$1" -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) | shuf -n 1) $wallpaper_dir && notify-send -i $wallpaper_dir "Random Wallpaper Chosen"

xwallpaper --zoom $wallpaper_dir
