#!/bin/sh

wallpaper_dir=~/.config/wall.png

[ -f "$1" ] && cp "$1" $wallpaper_dir

[ -d "$1" ] && cp $(find "$1" -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) | shuf -n 1) $wallpaper_dir

xwallpaper --zoom $wallpaper_dir
