#!/bin/sh

echo "-- Full Install --"

echo "-- Get Repositories --"
bash submudule-update
echo "-- Get Repositories End"

bash install-scripts/install-utilities
bash install-scripts/install-coder-tools
bash install-scripts/install-fonts
bash install-scripts/install-steam
bash install-scripts/install-email
bash install-scripts/install-virtual-machine

bash suckless-configs/full-instalation &
bash setup-scripts/personal-setups &
bash setup-scripts/setting-transmission &
bash setup-scripts/citrix-config &
bash custom-fastfetch/sync-to-computer &

bash local-preservation-state/dmc3_saves/update-state &
bash local-preservation-state/transmission_remote_config/update-state &
wait

echo "-- Autoremove --"
sudo pacman -R $(sudo pacman -Qdtq)
echo "-- Autoremove End --"

echo "-- Full Install End --"
