#!/bin/sh

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

echo "-- Installing Dependencies --"

# Installing dependencies
xargs -rxa $INSTALL_SCRIPT_PATH/dependencies -- sudo pacman -Sy --noconfirm --

# Install yay
(
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay
)

echo "-- Installing Dependencies End --"

echo "-- Install Utilities --"

xargs -rxa $SCRIPTPATH/utilities -- sudo pacman -Sy --noconfirm --

echo "-- Install Utilities End --"

echo "-- Install Yay Utilities --"

xargs -rxa $SCRIPTPATH/yay-programs -- yay --noconfirm --aur --answerclean All --answerdiff None --

echo "-- Install Yay Utilities End --"
