#!/bin/sh

echo "-- Configure Personal Scripts --"

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PERSONALSCRIPTPATH=$SCRIPTPATH/custom-scripts

[ -d ~/.config/custom-scripts ] && rm -rf ~/.config/custom-scripts

cp -r $PERSONALSCRIPTPATH ~/.config

echo "All the personal scripts were added/updated"

echo "-- Configure Personal Scripts End --"

echo "-- Configure Fastfetch Scripts --"
FASTFETCHSCRIPTPATH=$SCRIPTPATH/fastfetch

[ -d ~/.config/fastfech ] && rm -rf ~/.config/fastfetch
cp -r $FASTFETCHSCRIPTPATH ~/.config

echo "-- Configure Fastfetch Scripts End --"
